name: CI/CD--Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-and-build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Deploying to virtual machine
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "hello"
            export PATH=$PATH:/home/teamalpha/.nvm/versions/node/v20.15.1/bin
            bash ~/centrifugo.sh
